Comment: >-
  A Hello World example demonstrating various state types of the Amazon States
  Language. It is composed of flow control states only, so it does not need
  resources to run.
StartAt: Lambda Invoke on S3 PUT
States:
  Lambda Invoke on S3 PUT:
    Type: Task
    Resource: arn:aws:states:::lambda:invoke
    OutputPath: $.Payload
    Parameters:
      Payload.$: $
      FunctionName: arn:aws:lambda:us-east-1:712887588535:function:projectInvokeS3:$LATEST
    Retry:
      - ErrorEquals:
          - Lambda.ServiceException
          - Lambda.AWSLambdaException
          - Lambda.SdkClientException
          - Lambda.TooManyRequestsException
        IntervalSeconds: 1
        MaxAttempts: 3
        BackoffRate: 2
    Next: Parallel
  Parallel:
    Type: Parallel
    Branches:
      - StartAt: Filter Violence
        States:
          Filter Violence:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              Payload.$: $
              FunctionName: >-
                arn:aws:lambda:us-east-1:712887588535:function:projectFilterViolence:$LATEST
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
            Next: detected violence
          detected violence:
            Type: Choice
            Default: Success
            Choices:
              - Variable: $.fightingPresent
                BooleanEquals: true
                Next: Create description and export video (1)
          Success:
            Type: Succeed
          Create description and export video (1):
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              Payload.$: $
              FunctionName: >-
                arn:aws:lambda:us-east-1:712887588535:function:projectExportVideoCreateDescpriptionPolice:$LATEST
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
            End: true
      - StartAt: Filter Fire
        States:
          Filter Fire:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              Payload.$: $
              FunctionName: >-
                arn:aws:lambda:us-east-1:712887588535:function:projectFilterFire:$LATEST
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
            Next: recognised fire
          recognised fire:
            Type: Choice
            Choices:
              - Variable: $.firePresent
                BooleanEquals: true
                Next: Create description and export video
            Default: Success (1)
          Success (1):
            Type: Succeed
          Create description and export video:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              Payload.$: $
              FunctionName: >-
                arn:aws:lambda:us-east-1:712887588535:function:projectCreateDescriptionAndExportVideo:$LATEST
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
            End: true
      - StartAt: FilterSomikingPerson
        States:
          FilterSomikingPerson:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              Payload.$: $
              FunctionName: >-
                arn:aws:lambda:us-east-1:712887588535:function:projectFilterPerson:$LATEST
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
            Next: PersonSmoking
          PersonSmoking:
            Type: Choice
            Choices:
              - Variable: $.personSmoking
                BooleanEquals: true
                Next: perform Post on Billboards
            Default: Success (2)
          perform Post on Billboards:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              Payload.$: $
              FunctionName: >-
                arn:aws:lambda:us-east-1:712887588535:function:projectPostOnBillboards:$LATEST
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
            End: true
          Success (2):
            Type: Succeed
    End: true
